language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t abjbda/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true abjbda/docker-react npm run test
      